### ISSUE TITLE
NTLM proxy auth not working when going from HTTP to HTTPS

### ISSUE THREAD

**Issue by ghost** [javaee/grizzly-ahc#4] opened 2017-06-10 06:29 UTC
https://github.com/AsyncHttpClient/async-http-client/issues/1264

**Comment by ghost** [comment] 2017-06-12 19:13
@afelisatti Do you have changes for this issue?  I don't have NTLM available to test with, so it will be difficult for me to properly verify.

**Comment by afelisatti** [comment] 2017-06-12 20:00
I'll upload my attempt at a test from way back when I reported this. We are currently trying to reproduce it but it could give you an idea of the problem.

**Comment by afelisatti** [comment] 2017-06-12 20:11
My main issue with the test is whether the proxy was setup correctly or not, I remember having a hard time with Jetty over it. We'll update it if we find anything else.

**Comment by ghost** [comment] 2017-06-13 07:34
@afelisatti Can you share an AHC debug log of the failed transition from HTTP to HTTPS with NTLM?

**Comment by fsgonz** [comment] 2017-06-16 13:21
I think there may be 2 problems concerning the http proxy -> https scenario.

1) Firstly, ahc attempts to establish a tunnel through the proxy, but in order to consider the tunnel established, it expects a 200 code response to the CONNECT command.
However, in the aforementioned scenario, the first response is a 407 as authentication is mandatory for the proxy (and the authentication is needed by the http proxy before the https tunnel). So when http header is parsed in https://github.com/javaee/grizzly-ahc/blob/master/src/main/java/com/ning/http/client/providers/grizzly/AhcEventFilter.java#L279,
further content is ignored. But we need to initiate further NTLM negotiation (message 1 type, message 2 type and process the message 3 type). I think this line prompts the ntlm negotiation to be interrupted.
I tried the following the change to make it process content after the 407:

        if (context.establishingTunnel && !HttpStatus.PROXY_AUTHENTICATION_REQUIRED_407.statusMatches(statusCode) ) {
            // finish request/response processing, because Grizzly itself
            // treats CONNECT traffic as part of request-response processing
            // and we don't want it be treated like that
            httpHeader.setExpectContent(false);
            return false;
        }

2) when the target is an https server, i think it expects to establish the tunnel before the NTLM negotiation. So it does not send the type 1 message though a proxy is in the middle and it does not sends a type 1 message in the header even if a 407 response is obtained from the connect http command.
This happens even if the former code addition is made not to interrupt the content parsing. I've added the logic to send the ntlm type 1 message  beforehand in the connect command even if the connection is secure here:

https://github.com/javaee/grizzly-ahc/blob/master/src/main/java/com/ning/http/util/AuthenticatorUtils.java#L104

            if (ntlmHeader != null) {
                proxyAuthorization = ntlmHeader;
            } else {
                String msg = NTLMEngine.INSTANCE.generateType1Msg();
                proxyAuthorization = "NTLM " + msg;                
            }

I think another option would be to send the type 1 message once the first 407 response is obtained even in the http proxy -> https scenario.
These changes pass the test provided by @afelisatti and the other tests in the project, but I'm not sure if this is correct. It also passes the authentication in a local test environment where we have a http proxy -> https scenario, where the http proxy is a MS ISA Server.
I add the ahc logs without the changes:

**Test 1 (Proxy and https server created in test):**

2017-06-16 10:05:31,411 [grizzly-ahc-kernel(1) SelectorRunner] DEBUG com.ning.http.client.providers.grizzly.AsyncHttpClientFilter - REQUEST: HttpRequestPacket (
   method=CONNECT
   url=127.0.0.1:60147
   query=null
   protocol=HTTP/1.0
   content-length=-1
   headers=[
      Host=127.0.0.1:60147
      User-Agent=AHC/1.0
      Connection=keep-alive
      Proxy-Connection=keep-alive]
)
2017-06-16 10:05:31,424 [qtp1113166893-10] DEBUG com.ning.http.client.async.NtlmHttpProxyToHttpsTest$1 - CONNECT request for 127.0.0.1:60147
2017-06-16 10:05:31,440 [AsyncHttpClient-Callback] DEBUG com.ning.http.client.providers.grizzly.AhcEventFilter - RESPONSE: HttpResponsePacket (
  status=407
  reason=Proxy Authentication Required
  protocol=HTTP/1.1
  content-length=0
  committed=false
  headers=[
      content-length=0
      proxy-authenticate=NTLM
      connection=keep-alive
      server=Jetty(8.1.1.v20120215)]
)
FAILED: httpProxyToHttpsTargetTest
java.lang.AssertionError: expected object to not be null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.assertNotNull(Assert.java:404)
	at org.testng.Assert.assertNotNull(Assert.java:389)


**Test 2 This app tries to connect to an https through an ISA http proxy:**

2017-06-16 12:16:45,583 [grizzly-ahc-kernel(1) SelectorRunner] DEBUG com.ning.http.client.providers.grizzly.AsyncHttpClientFilter - REQUEST: HttpRequestPacket (
   method=CONNECT
   url=127.0.0.1:41180
   query=null
   protocol=HTTP/1.0
   content-length=-1
   headers=[
      Host=127.0.0.1:41180
      User-Agent=AHC/1.0
      Connection=keep-alive
      Proxy-Connection=keep-alive]
)
2017-06-16 12:16:45,596 [AsyncHttpClient-Callback] DEBUG com.ning.http.client.providers.grizzly.AhcEventFilter - RESPONSE: HttpResponsePacket (
  status=407
  reason=Proxy Authentication Required ( The ISA Server requires authorization to fulfill the request. Access to the Web Proxy filter is denied.  )
  protocol=HTTP/1.1
  content-length=716
  committed=false
  headers=[
      via=1.1 FABIAN-9F8A6B43
      proxy-authenticate=Negotiate
      connection=close
      proxy-connection=close
      pragma=no-cache
      cache-control=no-cache
      content-type=text/html
      content-length=716]
)
jun 16, 2017 12:16:45 PM org.glassfish.grizzly.filterchain.DefaultFilterChain execute
ADVERTENCIA: GRIZZLY0013: Exception during FilterChain execution
java.lang.NullPointerException
	at org.glassfish.grizzly.http.HttpClientFilter$ClientHttpResponseImpl.getProcessingState(HttpClientFilter.java:714)
	at com.ning.http.client.providers.grizzly.HttpTransactionContext.currentTransaction(HttpTransactionContext.java:134)
	at com.ning.http.client.providers.grizzly.AhcEventFilter.onHttpHeaderError(AhcEventFilter.java:255)
	at org.glassfish.grizzly.http.HttpCodecFilter.handleRead(HttpCodecFilter.java:627)
	at org.glassfish.grizzly.http.HttpClientFilter.handleRead(HttpClientFilter.java:175)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:539)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)


Notice that in both cases the proxy authentication is not added in the first http request and the test fails once the first 407 response is obtained.

**Comment by fsgonz** [comment] 2017-06-16 15:09
I've added a PR with the changes mentioned above.

https://github.com/javaee/grizzly-ahc/pull/8

**Closed as completed** 2017-06-22 17:37 UTC
Labels: bug

**Comment by afelisatti** [comment] 2017-06-22 18:12
@rlubke, now that there are no more reported issues is there a time frame for a release? Thanks.

**Comment by ghost** [comment] 2017-06-22 18:19
@afelisatti Already done and announced on the discussion list.

**Comment by afelisatti** [comment] 2017-06-22 18:30
Thanks!
